# Generated by Django 2.1.2 on 2018-10-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_otherimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherImages',
        ),
    ]
