# Generated by Django 2.1.2 on 2018-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_otherimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagesforblogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagesforblogs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Imageforblogs',
        ),
    ]
