# Generated by Django 2.1.2 on 2018-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181025_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
