from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length = 250)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = 'images/')

    introduction = models.TextField(blank=True, default='')
    prerequisite = models.TextField(blank=True, default='')
    pr_list1 =  models.TextField(blank=True, default='')
    pr_list2 =  models.TextField(blank=True, default='')
    pr_list3 =  models.TextField(blank=True, default='')
    pr_list4 =  models.TextField(blank=True, default='')
    pr_list5 =  models.TextField(blank=True, default='')
    pr_list6 =  models.TextField(blank=True, default='') 
    pr_list7 =  models.TextField(blank=True, default='')
    pr_list8 =  models.TextField(blank=True, default='')
    pr_list9 =  models.TextField(blank=True, default='')
    pr_list10 =  models.TextField(blank=True, default='')
    head1 = models.TextField(blank=True, default='')
    content1 =  models.TextField(blank=True, default='')
    h1_list1 =  models.TextField(blank=True, default='')
    h1_list2 =  models.TextField(blank=True, default='')
    h1_list3 =  models.TextField(blank=True, default='')
    h1_list4 =  models.TextField(blank=True, default='')
    h1_list5 =  models.TextField(blank=True, default='')
    h1_list6 =  models.TextField(blank=True, default='') 
    h1_list7 =  models.TextField(blank=True, default='')
    h1_list8 =  models.TextField(blank=True, default='')
    h1_list9 =  models.TextField(blank=True, default='')
    h1_list10 =  models.TextField(blank=True, default='')
    image1 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head2 = models.TextField(blank=True, default='')
    content2 =  models.TextField(blank=True, default='')
    h2_list1 =  models.TextField(blank=True, default='')
    h2_list2 =  models.TextField(blank=True, default='')
    h2_list3 =  models.TextField(blank=True, default='')
    h2_list4 =  models.TextField(blank=True, default='')
    h2_list5 =  models.TextField(blank=True, default='')
    h2_list6 =  models.TextField(blank=True, default='') 
    h2_list7 =  models.TextField(blank=True, default='')
    h2_list8 =  models.TextField(blank=True, default='')
    h2_list9 =  models.TextField(blank=True, default='')
    h2_list10 =  models.TextField(blank=True, default='')
    image2 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head3 = models.TextField(blank=True, default='')
    content3 =  models.TextField(blank=True, default='')
    h3_list1 =  models.TextField(blank=True, default='')
    h3_list2 =  models.TextField(blank=True, default='')
    h3_list3 =  models.TextField(blank=True, default='')
    h3_list4 =  models.TextField(blank=True, default='')
    h3_list5 =  models.TextField(blank=True, default='')
    h3_list6 =  models.TextField(blank=True, default='') 
    h3_list7 =  models.TextField(blank=True, default='')
    h3_list8 =  models.TextField(blank=True, default='')
    h3_list9 =  models.TextField(blank=True, default='')
    h3_list10 =  models.TextField(blank=True, default='')
    image3 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head4 = models.TextField(blank=True, default='')
    content4 =  models.TextField(blank=True, default='')
    h4_list1 =  models.TextField(blank=True, default='')
    h4_list2 =  models.TextField(blank=True, default='')
    h4_list3 =  models.TextField(blank=True, default='')
    h4_list4 =  models.TextField(blank=True, default='')
    h4_list5 =  models.TextField(blank=True, default='')
    h4_list6 =  models.TextField(blank=True, default='') 
    h4_list7 =  models.TextField(blank=True, default='')
    h4_list8 =  models.TextField(blank=True, default='')
    h4_list9 =  models.TextField(blank=True, default='')
    h4_list10 =  models.TextField(blank=True, default='')
    image4 = models.ImageField(upload_to = 'images/', blank=True, null=True)    
    head5 = models.TextField(blank=True, default='')
    content5 =  models.TextField(blank=True, default='')
    h5_list1 =  models.TextField(blank=True, default='')
    h5_list2 =  models.TextField(blank=True, default='')
    h5_list3 =  models.TextField(blank=True, default='')
    h5_list4 =  models.TextField(blank=True, default='')
    h5_list5 =  models.TextField(blank=True, default='')
    h5_list6 =  models.TextField(blank=True, default='') 
    h5_list7 =  models.TextField(blank=True, default='')
    h5_list8 =  models.TextField(blank=True, default='')
    h5_list9 =  models.TextField(blank=True, default='')
    h5_list10 =  models.TextField(blank=True, default='')
    image5 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head6 = models.TextField(blank=True, default='')
    content6 =  models.TextField(blank=True, default='')
    h6_list1 =  models.TextField(blank=True, default='')
    h6_list2 =  models.TextField(blank=True, default='')
    h6_list3 =  models.TextField(blank=True, default='')
    h6_list4 =  models.TextField(blank=True, default='')
    h6_list5 =  models.TextField(blank=True, default='')
    h6_list6 =  models.TextField(blank=True, default='') 
    h6_list7 =  models.TextField(blank=True, default='')
    h6_list8 =  models.TextField(blank=True, default='')
    h6_list9 =  models.TextField(blank=True, default='')
    h6_list10 =  models.TextField(blank=True, default='')
    image6 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head7 = models.TextField(blank=True, default='')
    content7 =  models.TextField(blank=True, default='')
    h7_list1 =  models.TextField(blank=True, default='')
    h7_list2 =  models.TextField(blank=True, default='')
    h7_list3 =  models.TextField(blank=True, default='')
    h7_list4 =  models.TextField(blank=True, default='')
    h7_list5 =  models.TextField(blank=True, default='')
    h7_list6 =  models.TextField(blank=True, default='') 
    h7_list7 =  models.TextField(blank=True, default='')
    h7_list8 =  models.TextField(blank=True, default='')
    h7_list9 =  models.TextField(blank=True, default='')
    h7_list10 =  models.TextField(blank=True, default='')
    image7 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head8 = models.TextField(blank=True, default='')
    content8 =  models.TextField(blank=True, default='')
    h8_list1 =  models.TextField(blank=True, default='')
    h8_list2 =  models.TextField(blank=True, default='')
    h8_list3 =  models.TextField(blank=True, default='')
    h8_list4 =  models.TextField(blank=True, default='')
    h8_list5 =  models.TextField(blank=True, default='')
    h8_list6 =  models.TextField(blank=True, default='') 
    h8_list7 =  models.TextField(blank=True, default='')
    h8_list8 =  models.TextField(blank=True, default='')
    h8_list9 =  models.TextField(blank=True, default='')
    h8_list10 =  models.TextField(blank=True, default='')
    image8 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head9 = models.TextField(blank=True, default='')
    content9 =  models.TextField(blank=True, default='')
    h9_list1 =  models.TextField(blank=True, default='')
    h9_list2 =  models.TextField(blank=True, default='')
    h9_list3 =  models.TextField(blank=True, default='')
    h9_list4 =  models.TextField(blank=True, default='')
    h9_list5 =  models.TextField(blank=True, default='')
    h9_list6 =  models.TextField(blank=True, default='') 
    h9_list7 =  models.TextField(blank=True, default='')
    h9_list8 =  models.TextField(blank=True, default='')
    h9_list9 =  models.TextField(blank=True, default='')
    h9_list10 =  models.TextField(blank=True, default='')
    image9 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    head10 = models.TextField(blank=True, default='')
    content10 =  models.TextField(blank=True, default='')
    h10_list1 =  models.TextField(blank=True, default='')
    h10_list2 =  models.TextField(blank=True, default='')
    h10_list3 =  models.TextField(blank=True, default='')
    h10_list4 =  models.TextField(blank=True, default='')
    h10_list5 =  models.TextField(blank=True, default='')
    h10_list6 =  models.TextField(blank=True, default='') 
    h10_list7 =  models.TextField(blank=True, default='')
    h10_list8 =  models.TextField(blank=True, default='')
    h10_list9 =  models.TextField(blank=True, default='')
    h10_list10 =  models.TextField(blank=True, default='')
    image10 = models.ImageField(upload_to = 'images/', blank=True, null=True)

    ex_img1 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    ex_img2 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    ex_img3 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    ex_img4 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    ex_img5 = models.ImageField(upload_to = 'images/', blank=True, null=True)
    url1 = models.URLField(max_length=250, blank=True, null=True)
    url2 = models.URLField(max_length=250, blank=True, null=True)
    url3 = models.URLField(max_length=250, blank=True, null=True)
    url4 = models.URLField(max_length=250, blank=True, null=True)
    url5 = models.URLField(max_length=250, blank=True, null=True)
 


    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:200]
    
    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')


class Imagesforblogs(models.Model):
    image = models.ImageField(upload_to = 'imagesforblogs/')

